language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master